name = "taj-dashboard"
compatibility_date = "2024-01-01"

[build]
command = "npm run pages:build"

[build.upload]
format = "service-worker"

[env.production]
name = "taj-dashboard"
route = "taj-dashboard.pages.dev/*"

[env.production.build]
command = "npm run pages:build" 